// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.5
// source: muun.proto

package muun

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Stock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ticker string  `protobuf:"bytes,1,opt,name=ticker,proto3" json:"ticker,omitempty"`
	Strike float64 `protobuf:"fixed64,2,opt,name=strike,proto3" json:"strike,omitempty"`
}

func (x *Stock) Reset() {
	*x = Stock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_muun_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stock) ProtoMessage() {}

func (x *Stock) ProtoReflect() protoreflect.Message {
	mi := &file_muun_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stock.ProtoReflect.Descriptor instead.
func (*Stock) Descriptor() ([]byte, []int) {
	return file_muun_proto_rawDescGZIP(), []int{0}
}

func (x *Stock) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *Stock) GetStrike() float64 {
	if x != nil {
		return x.Strike
	}
	return 0
}

type GetStockPriceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ticker string `protobuf:"bytes,1,opt,name=ticker,proto3" json:"ticker,omitempty"`
}

func (x *GetStockPriceRequest) Reset() {
	*x = GetStockPriceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_muun_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStockPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockPriceRequest) ProtoMessage() {}

func (x *GetStockPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_muun_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockPriceRequest.ProtoReflect.Descriptor instead.
func (*GetStockPriceRequest) Descriptor() ([]byte, []int) {
	return file_muun_proto_rawDescGZIP(), []int{1}
}

func (x *GetStockPriceRequest) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

type GetStockPriceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Strike float64 `protobuf:"fixed64,1,opt,name=strike,proto3" json:"strike,omitempty"`
}

func (x *GetStockPriceResponse) Reset() {
	*x = GetStockPriceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_muun_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStockPriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockPriceResponse) ProtoMessage() {}

func (x *GetStockPriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_muun_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockPriceResponse.ProtoReflect.Descriptor instead.
func (*GetStockPriceResponse) Descriptor() ([]byte, []int) {
	return file_muun_proto_rawDescGZIP(), []int{2}
}

func (x *GetStockPriceResponse) GetStrike() float64 {
	if x != nil {
		return x.Strike
	}
	return 0
}

var File_muun_proto protoreflect.FileDescriptor

var file_muun_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6d, 0x75, 0x75, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x75,
	0x75, 0x6e, 0x22, 0x37, 0x0a, 0x05, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x74,
	0x69, 0x63, 0x6b, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x69, 0x63,
	0x6b, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x69, 0x6b, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x06, 0x73, 0x74, 0x72, 0x69, 0x6b, 0x65, 0x22, 0x2e, 0x0a, 0x14, 0x47,
	0x65, 0x74, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x22, 0x2f, 0x0a, 0x15, 0x47,
	0x65, 0x74, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x69, 0x6b, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x73, 0x74, 0x72, 0x69, 0x6b, 0x65, 0x32, 0x5a, 0x0a, 0x0c,
	0x53, 0x74, 0x6f, 0x63, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4a, 0x0a, 0x0d,
	0x47, 0x65, 0x74, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x2e,
	0x6d, 0x75, 0x75, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x69,
	0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x6d, 0x75, 0x75, 0x6e,
	0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x1a, 0x5a, 0x18, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6c, 0x6d, 0x6f, 0x67, 0x6f, 0x72, 0x69, 0x2f,
	0x6d, 0x75, 0x75, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_muun_proto_rawDescOnce sync.Once
	file_muun_proto_rawDescData = file_muun_proto_rawDesc
)

func file_muun_proto_rawDescGZIP() []byte {
	file_muun_proto_rawDescOnce.Do(func() {
		file_muun_proto_rawDescData = protoimpl.X.CompressGZIP(file_muun_proto_rawDescData)
	})
	return file_muun_proto_rawDescData
}

var file_muun_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_muun_proto_goTypes = []interface{}{
	(*Stock)(nil),                 // 0: muun.Stock
	(*GetStockPriceRequest)(nil),  // 1: muun.GetStockPriceRequest
	(*GetStockPriceResponse)(nil), // 2: muun.GetStockPriceResponse
}
var file_muun_proto_depIdxs = []int32{
	1, // 0: muun.StockService.GetStockPrice:input_type -> muun.GetStockPriceRequest
	2, // 1: muun.StockService.GetStockPrice:output_type -> muun.GetStockPriceResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_muun_proto_init() }
func file_muun_proto_init() {
	if File_muun_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_muun_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_muun_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStockPriceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_muun_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStockPriceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_muun_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_muun_proto_goTypes,
		DependencyIndexes: file_muun_proto_depIdxs,
		MessageInfos:      file_muun_proto_msgTypes,
	}.Build()
	File_muun_proto = out.File
	file_muun_proto_rawDesc = nil
	file_muun_proto_goTypes = nil
	file_muun_proto_depIdxs = nil
}
